### ISSUE TITLE
Maybe would be nice to add amazon S3 v3 support

### ISSUE THREAD

**Issue by svycka** [bushbaby/BsbFlysystem#14]
Currently league/flysystem-aws-s3-v3 is not supported only league/flysystem-aws-s3-v2

**Comment by basz** [comment]
I'm open to PR's...

Not gonna happen by me anytime soon as I don't use that adapter atm.

**Comment by basz** [comment]
via https://github.com/bushbaby/BsbFlysystem/releases/tag/1.2.2
