### ISSUE TITLE
Feature suggestion RenameUpload

### ISSUE THREAD

**Issue by svycka** [bushbaby/BsbFlysystem#18]
Would you accept Zend\Filter\File\RenameUpload implementation with filesystem into this project or this is to much?

**Comment by basz** [comment]
Uh I don’t see how these are connected?


Could you explain please?


> On 9 sep. 2015, at 16:33, Vytautas Stankus <notifications@github.com> wrote:
> 
> Would you accept Zend\Filter\File\RenameUpload implementation with filesystem into this project or this is to much?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/bushbaby/BsbFlysystem/issues/18>.
> 



bushbaby multimedia ontwerp & uitvoering
bas@bushbaby.nl <mailto:bas@bushbaby.nl> | +31(0)6 2897 7426 | kvk 34125878

**Comment by svycka** [comment]
for now Zend\Filter\File\RenameUpload can be used to move uploaded files in local filesystem lets say folder `/public/images/myimage.jpg` and flysystem could replace local system and files could be saved on any flysystem supported adapters
example:
```php
$filter = new \BsbFlysystem\Filter\File\RenameUpload([
    'target' => 'path/to/file.txt',
    'filesystem' => $this->getServiceLocator()->get('BsbFlysystemManager')->get('awss3')
]);
$filter->filter($uploaded_file);
```
and uploaded file would end up in amazon S3 server with key `path/to/file.txt`

For more info http://framework.zend.com/manual/current/en/modules/zend.filter.file.rename-upload.html

**Comment by basz** [comment]
I know what RenameUpload does. I like this idea, just no time to write it the moment. Do you think it is hard to write? Please go ahead if you need it. I’ll merge happily



> On 9 sep. 2015, at 16:48, Vytautas Stankus <notifications@github.com> wrote:
> 
> for now Zend\Filter\File\RenameUpload can be used to move uploaded files in local filesystem lets say folder /public/images/myimage.jpg and flysystem could replace local system and files could be saved on any flysystem supported adapters
> example:
> 
> $filter = new \BsbFlysystem\Filter\File\RenameUpload([
>     'target' => 'path/to/file.txt',
>     'filesystem' => $this->getServiceLocator()->get('BsbFlysystemManager')->get('awss3')
> ]);
> $filter->filter($uploaded_file);
> and uploaded file would end up in amazon S3 server with key path/to/file.txt
> 
> For more info http://framework.zend.com/manual/current/en/modules/zend.filter.file.rename-upload.html <http://framework.zend.com/manual/current/en/modules/zend.filter.file.rename-upload.html>
> —
> Reply to this email directly or view it on GitHub <https://github.com/bushbaby/BsbFlysystem/issues/18#issuecomment-138934575>.
> 



bushbaby multimedia ontwerp & uitvoering
bas@bushbaby.nl <mailto:bas@bushbaby.nl> | +31(0)6 2897 7426 | kvk 34125878

**Comment by svycka** [comment]
Ok I will try, it should be easy just few methods to override i think.
