### ISSUE TITLE
custom adapter

### ISSUE THREAD

**Issue by taxist08** [bushbaby/BsbFlysystem#4]
Hi friend!
A have use custonm adapter for my file storage.
How i can do this?

**Comment by basz** [comment]
Hello, I don't understand your question... Explain to me what is it you are trying to achieve? What have you tried and what is failing you?

**Comment by taxist08** [comment]
I have my storage, 
I need to add an adapter to use it, 
I have to file a property AdapterManagerFactory.php  $adapterFaktoroMap add your adapter, 
as you can do without modify this file?

16.03.2015 12:48, Bas Kamer <notifications@github.com>
>Hello, I don't understand your question... Explain to me what is it you are trying to achieve? What have you tried and what is failing you?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bushbaby/BsbFlysystem/issues/4#issuecomment-81575394


-- реклама -----------------------------------------------------------
Не дорогой качественный хостинг. Приятные сюрпризы для каждого!
http://freehost.com.ua/unix/

**Comment by basz** [comment]
Do I understand you correctly if you say you need to add a custom adapter to the adapter manager?

Have you tried adding your adapter to the the adapter manager configuration? https://github.com/bushbaby/BsbFlysystem#adaptermanager

```
        'adapter_manager'    => [
            'config'        => [
                'invokables' => [

                ]
            ],
            'lazy_services' => [
            ],

```

**Comment by taxist08** [comment]
'adapters' => [
            'local_files' => [
                'type' => 'local',
                'options' => [
                    'root' => './fs_local'
                ],
            ],
            'my_ad'       => [
                'type'    => 'my_ad',
                'options'  => [
                    'key'     => 'my_ad',
                    'api_url' => 'http://files.local/api/v2/fs/',
                ],
            ],
            'invokables' => [
                'my_ad'      => 'My\FilesystemService\Adapter\Factory\MyAdapterFactory',
            ]
        ],

**Comment by basz** [comment]
move 
```
'invokables' => [
            'my_ad'      => 'My\FilesystemService\Adapter\Factory\MyAdapterFactory',
        ]
```

to the bsb_flysystem->adapter_manager->config key as in the previous example

Also you define a factory in the invokables array which doesn't make sense. It's either an invokable or it's a factory and it should be in the factories keys.

**Comment by taxist08** [comment]
Message:

    Unknown adapter 'type' ('my_ad')

**Comment by basz** [comment]
1. Show me your complete (merged) configuration (post it a gist.github.com)
2. Is your adapter create by a factory or can it be instantiated without a specific factory (it is invokable without dependancies)?

**Comment by taxist08** [comment]
Hm....
I use old version...
I try  composer require "bushbaby/flysystem:~1.0" and have:
"The requested package bushbaby/flysystem could not be found in any version, there may be a typo in the package name."

**Comment by basz** [comment]
BsbFlysystem is still prerelease at beta1

Tell your project about a [minimum stability](https://getcomposer.org/doc/04-schema.md#minimum-stability)

```
"minimum-stability": "dev",
```

And tell composer to use the prerelease version by requirering "bushbaby/flysystem:~1.0@dev"

**Comment by taxist08** [comment]
Ok.
 I create fork, see please

**Comment by basz** [comment]
?

**Comment by basz** [comment]
You can add a custom adapter completely in userland by changing the BsbFlysystem configuration.

These are the steps you need to take to add one:

1. Write your adapter
`My\FilesystemService\Adapter\MyAdapter`

2. Write a Factory for it
`My\FilesystemService\Adapter\Factory\MyAdapterFactory`

3. Register the service to the adapter (plugin) manager by editing a copy of the BsbFlysystem configuration. 
`cp ./vendor/bushbaby/flysystem/config/bsb_flysystem.global.php.dist ./config/autoload/bsb_flysystem.global.php`
add the following to it as a subbranch of bob_flysystem
```
'adapter_manager'    => [
    'config'        => [   
        'factories' => [
            'my_custom_adapter' => 'My\FilesystemService\Adapter\Factory\MyAdapterFactory',
        ],
    ],
],
```
That's it! Now you can use `my_custom_adapter` as an adapter `type` in the adapter configuration.

**Comment by basz** [comment]
@taxist08 are you succeeding?

**Comment by taxist08** [comment]
Hi, I wrote an heir AdapterManagerFactory.php
and overloaded method kreateServise ()

**Comment by iam-merlin** [comment]
hi @basz, just a little question. I have a rapid look to the code... why not just add in file `bushbaby/flysystem/src/Service/Factory/AdapterManagerFactory.php:57` somthing like ` $this->adapterMap = ArrayUtils::merge($this->adapterMap, isset($config['adapter_map']) ? $config['adapter_map'] : []);`.

**Comment by basz** [comment]
@iam-merlin That would enable you to configure the adapter_map on runtime. Sound like a reasonable idea to me. It would eliminate the constructor that is just there for testing purposes

Are you able to write a PR for that (including the tests and documentation)?

**Comment by iam-merlin** [comment]
can do that

**Comment by basz** [comment]
awesome! let's move further discussion (if any) to the separately opened issue
