### ISSUE TITLE
AWS SDK v3 request config changed

### ISSUE THREAD

**Issue by bstoney** [bushbaby/BsbFlysystem#40]
The AWS SDK v3 configuration key used to set the Guzzle request options has changed from `request.options` to `http` see [Configuration for the AWS SDK for PHP version 3](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html)

**Comment by basz** [comment]
Have any info on when this changed? Are you able to provide a PR?

**Comment by bstoney** [comment]
I far as I can tell it has always been the case for version 3. Yes I'll provide a PR.
