### ISSUE TITLE
Does version 5.0 has any BC breaks from version 4.x?

### ISSUE THREAD

**Issue by svycka** [bushbaby/BsbFlysystem#52]
There are no warnings about BC breaks but still, a major version released maybe something changed?

**Comment by basz** [comment]
I think only support for php71 was dropped

**Comment by svycka** [comment]
this is not BC break :D I am more concerned about:

> removed dependency on zendframework/zend-servicemanager, now psr-container is enough

**Comment by basz** [comment]
Yeah, that *should* not BC... Just gives more options to use other DI implementations... But *not* using that myself...

**Comment by svycka** [comment]
O kay will try. thanks.
