### ISSUE TITLE
zendframework/zend-cache as optional dependency?

### ISSUE THREAD

**Issue by snapshotpl** [bushbaby/BsbFlysystem#53]
Looks like `zendframework/zend-cache` is used in some case where you need already require it. I think this library can be required as suggested and dev dependecy.

@basz what are you think?

**Comment by snapshotpl** [comment]
To make cache work we need also `League\Flysystem\Cached\CachedAdapter` which is optional dependency, so without this require `zendframework/zend-cache` does't make a sense. 

https://github.com/bushbaby/BsbFlysystem/blob/747a7414d4be41eb24f3aa9fac54fdaef1ad4d69/src/Filesystem/Factory/FilesystemFactory.php#L85

**Comment by snapshotpl** [comment]
@basz ping

**Comment by basz** [comment]
I agree. Yet, minor and BC.

**Comment by snapshotpl** [comment]
Cool, I will prepare PR after resolve current pending two.
