### ISSUE TITLE
Tag new version for Laminas

### ISSUE THREAD

**Issue by FrankHouweling** [bushbaby/BsbFlysystem#57]
Hi,

I see this library was transitioned to Laminas with PR #56, but this change is still in the master branch.

We would like to (fully) transition to Laminas, and this library is holding us back, because we prefer not to have any dev-master dependencies.

Is there any way you could tag a new (major) release?

Thank you for your help, and your contributions to the open source community,

~ Frank

**Comment by basz** [comment]
tagged! thanks I forgot...
