### ISSUE TITLE
TODO Rework AdapterFactory so it can modify the adapter_map on runtime from configuration 

### ISSUE THREAD

**Issue by basz** [bushbaby/BsbFlysystem#9]
see https://github.com/bushbaby/BsbFlysystem/issues/4#issuecomment-96522829

- [ ] rework factory to allow runtime adapter_map
- [ ] remove constructor as it becomes useless
- [ ] tweak unittest
- [ ] documentation

**Comment by iam-merlin** [comment]
@basz If the adapter_map can be set in configuration, we should consider to create a second issue to remove constructor (as a no BC break, it's explicitly mark for testing) ? In my point of view, this constructor is useless and add complexity.

**Comment by basz** [comment]
jip, see todo's
